name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  cs-check:
    runs-on: ubuntu-latest
    name: CS Check

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - run: composer install --no-progress --prefer-dist

      - run: composer cs-check

  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_sqlite
          coverage: none

      - run: composer install --no-progress --prefer-dist

      - run: ./vendor/bin/phpunit
